spring:
  application:
    name: tj_lab2_advanced
  profiles:
    active: dev

greeting-message: "Well hello there!"

management:
  endpoints:
    web:
      exposure:
        include: *
  info:
    env:
      enabled: true
