spring:
  application:
    name: tj_lab2_advanced
  profiles:
    active: dev

message: "Well hello there!"

management:
  endpoints:
    web:
      exposure:
        include: info,metrics,health
  info:
    env:
      enabled: true
